# .readthedocs.yml

version: 2

python:
  version: 3.6
  install:
    - requirements: requirements.txt
    - requirements: requirements_test.txt
    - requirements: requirements_dev.txt

sphinx:
  configuration: docs/conf.py
